targets:
  $default:
    builders:
      riverpod_generator:riverpod_generator:
        options:
          # Riverpod код генерация настройки
          riverpod_generator:
            provider_name_prefix: ""
            provider_name_suffix: "Provider"
      
      freezed:json_annotation:
        enabled: true
        
      json_serializable:json_serializable:
        options:
          # JSON сериализация настройки
          any_map: true
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          include_if_null: false
